[FEAT] 레스토랑 전체 조회 기능 구현
CHEFLEA/Cheflea-Server pull request #36
Opened 2024-08-22 21:39 UTC by Kim-TaeUk

##  Related Issue 🍀
- close #6 

## Key Changes 🔑
- db에서 전체 `restaurant` 조회 후, `loginUser`가 좋아요 한 `restaurant`인지 확인하여 처리해주는 로직입니다.

2024-08-22 21:40 UTC, Kim-TaeUk commented on src/main/java/up/value/chefleaserver/service/RestaurantService.java
> +                .toList();
contains() 대신 anyMatch()를 사용해봤습니다~

2024-08-23 08:59 UTC, eundeang commented on src/main/java/up/value/chefleaserver/service/RestaurantService.java
> +                .toList();
오호잉 지원하눈 메소드가 참말로 많네유~

2024-08-23 09:07 UTC, eundeang approved these changes
LGTM!

2024-08-23 09:08 UTC, eundeang requested changes

2024-08-23 09:08 UTC, eundeang commented on src/main/java/up/value/chefleaserver/service/RestaurantService.java
> +                .map(restaurant -> {
옹 근데 isLiked 메서드 만들어놨는데...

2024-08-23 12:52 UTC, Kim-TaeUk commented on src/main/java/up/value/chefleaserver/service/RestaurantService.java
> +                .map(restaurant -> {
확인해보니까 User랑 Popup의 관계에서 like를 판단하는 메서드라서 재사용은 안될 것 같아유!

새로 메서드를 정의해서 사용하든지 해야할 것 같은데, 어떻게 할까요? 

제 생각은 반복되는 로직있으면 그때 메서드로 빼도 될 것 같습니다.

2024-08-23 13:40 UTC, eundeang commented on src/main/java/up/value/chefleaserver/service/RestaurantService.java
> +                .map(restaurant -> {
오홍 그러면 될거 같아욥! 고생해쓤다

2024-08-23 13:40 UTC, eundeang approved these changes

2024-08-23 22:01 UTC, merged